
-- ANTA Showroom V8 - Supabase/Postgres schema

create table if not exists retailer_profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  retailer_name text not null,
  contact_name text,
  email text,
  role text not null default 'retailer' check (role in ('admin','retailer')),
  active boolean not null default true,
  allowed_categories text[] default '{}',
  created_at timestamptz not null default now()
);

create table if not exists download_events (
  id bigint generated by default as identity primary key,
  retailer_id uuid references retailer_profiles(id) on delete set null,
  sku text,
  event_type text not null check (
    event_type in ('product_view','product_select','download_info','download_images','download_complete_pack')
  ),
  selected_count integer,
  download_mode text,
  session_id text,
  created_at timestamptz not null default now()
);

create table if not exists enrichment_reviews (
  id bigint generated by default as identity primary key,
  sku text not null,
  source_url text,
  candidate_title text,
  confidence numeric,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references retailer_profiles(id) on delete set null,
  reviewed_at timestamptz,
  notes text
);

create index if not exists idx_download_events_retailer on download_events(retailer_id);
create index if not exists idx_download_events_sku on download_events(sku);
create index if not exists idx_enrichment_reviews_sku on enrichment_reviews(sku);

-- Enable RLS
alter table retailer_profiles enable row level security;
alter table download_events enable row level security;
alter table enrichment_reviews enable row level security;

-- Retailers can read their own profile
drop policy if exists retailer_read_own_profile on retailer_profiles;
create policy retailer_read_own_profile
on retailer_profiles for select
using (auth.uid() = auth_user_id);

-- Admins can read all profiles
drop policy if exists admin_read_all_profiles on retailer_profiles;
create policy admin_read_all_profiles
on retailer_profiles for select
using (
  exists (
    select 1 from retailer_profiles rp
    where rp.auth_user_id = auth.uid() and rp.role = 'admin' and rp.active = true
  )
);

-- Authenticated users may insert their own download events
drop policy if exists retailer_insert_download_events on download_events;
create policy retailer_insert_download_events
on download_events for insert
with check (
  exists (
    select 1 from retailer_profiles rp
    where rp.id = retailer_id and rp.auth_user_id = auth.uid() and rp.active = true
  )
);

-- Admins can read download events
drop policy if exists admin_read_download_events on download_events;
create policy admin_read_download_events
on download_events for select
using (
  exists (
    select 1 from retailer_profiles rp
    where rp.auth_user_id = auth.uid() and rp.role = 'admin' and rp.active = true
  )
);

-- Admins manage enrichment reviews
drop policy if exists admin_manage_enrichment_reviews on enrichment_reviews;
create policy admin_manage_enrichment_reviews
on enrichment_reviews for all
using (
  exists (
    select 1 from retailer_profiles rp
    where rp.auth_user_id = auth.uid() and rp.role = 'admin' and rp.active = true
  )
)
with check (
  exists (
    select 1 from retailer_profiles rp
    where rp.auth_user_id = auth.uid() and rp.role = 'admin' and rp.active = true
  )
);
